import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { AppSidebar } from "@/components/common/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import { ApolloWrapper } from "@/graphql/ApolloWrapper";

import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ApolloWrapper>
					<SidebarProvider>
						<div className={"flex w-screen flex-row"}>
							<AppSidebar />
							<div className={"h-screen w-full overflow-hidden"}>
								<div className="mx-auto h-full">{children}</div>
							</div>
						</div>
					</SidebarProvider>
				</ApolloWrapper>
				<Toaster />
			</body>
		</html>
	);
}
