import type { ReactNode } from "react";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import { AppSidebar } from "@/components/common/AppSidebar";
import { GqlClientProvider } from "@/components/common/GqlClientProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modal,
}: Readonly<{
	children: ReactNode;
	modal: ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<GqlClientProvider>
					<SidebarProvider>
						<div className={"flex w-screen flex-row"}>
							<AppSidebar />
							<div className={"h-screen w-full overflow-hidden"}>
								<div className="mx-auto h-full">
									{children}
									{modal}
								</div>
							</div>
						</div>
					</SidebarProvider>
					<ReactQueryDevtools />
				</GqlClientProvider>
				<Toaster />
			</body>
		</html>
	);
}
