import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Header } from "@/components/common/Header";
import { Toaster } from "@/components/ui/sonner";
import { AccountProvider } from "@/context/AccountContext";
import { ApolloWrapper } from "@/graphql/ApolloWrapper";

import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Header />
				<ApolloWrapper>
					<AccountProvider>
						<div
							className={
								"absolute top-0 left-0 h-screen w-screen overflow-hidden py-16"
							}
						>
							<div className="container mx-auto h-full">
								{children}
							</div>
						</div>
					</AccountProvider>
				</ApolloWrapper>
				<Toaster />
			</body>
		</html>
	);
}
